# Generated by Django 4.2.4 on 2023-10-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
                ('city', models.TextField(max_length=100)),
            ],
        ),
    ]
