# Generated by Django 4.2.4 on 2023-10-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peoples.person')),
                ('work_place', models.TextField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=8, max_digits=10)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='peoples.person')),
            ],
            bases=('peoples.person',),
        ),
    ]
